### ISSUE TITLE
Final weights look strange

### ISSUE THREAD

**Issue by M145** [emunozh/GREGWT#1]
I follow readme to run GREGWT . 
But TAE are very high and Final weights look strange.
Can anyone help me?

summary(Weights.GREGWT$final_weights)
       V1
Min.   :    0.00
1st Qu.:    0.00
Median :   13.32
Mean   :  167.67
3rd Qu.:  176.52
Max.   :53549.45

**Comment by emunozh** [comment]
Could you provide the code you use to run gregwt?

**Comment by emunozh** [comment]
Indeed there was a small error on the code, thnks! 
see: 8c37470ddf4b317158b90446b07c2afc3905b021

you can generate a small plot to see where the error is allocated:

``` R
plot(Weights.GREGWT)
```

Now we have: **PSAE = 9.3e-02** and **TAE=1.6e+3**

``` R
summary(Weights.GREGWT$final_weights)
```

```
       V1        
 Min.   :   0.0  
 1st Qu.: 126.6  
 Median : 158.9  
 Mean   : 167.7  
 3rd Qu.: 197.2  
 Max.   :1676.5
```
