### ISSUE TITLE
error when running prepareData()

### ISSUE THREAD

**Issue by tyokota** [emunozh/GREGWT#2]
What does this error mean? Is there a place to specify the formula in prepareData()?

Error in terms.formula(object, data = data) : 
  '.' in formula and no 'data' argument

**Comment by emunozh** [comment]
can you provide the code you are tying to run so I can reproduce the error?

**Comment by tyokota** [comment]
`data_in <- prepareData(census=ACS.census,
                       survey=BRFSS.survey,
                       census_area_id = 1,
                       census_categories=seq(2,26),
                       pop_benchmark=c(2,7),
                       survey_id=1,
                       survey_categories=seq(2,7),
                       survey_weights="X_LLCPWT"
)`

**Comment by tyokota** [comment]
I figured out the issue. There were a few variables with spaces. I had used `var name` initially. I eventually used `make.names()`.
